config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#home'
  
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#logout'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'


  resources :games do 
    resources :posts do
      resources :comments
    end
  end

  resources :posts

  resources :users
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :posts
    has_many :users, through: :posts

    scope :search, -> (params){where("Lower(title)= ?", params)}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :comments

  validates :game_name, :gamer_tag, :platform, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts
    has_many :comments
    has_many :games, through: :posts

    validates :username, :email, presence: true
    validates :username, :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?


    private 

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end

    def logged_in?
        !!current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


    def create 
        @game = Game.find_by_id(params[:game_id])
        @post = Post.find_by_id(params[:post_id])
        @comment = @post.comments.create(comments_params)
        @comment.user_id = @post.user_id
        @comment.save
        if @comment.save
            redirect_to game_post_path(@game, @post)
        else
            redirect_to game_post_path(@game, @post)
        end
    end

    private

    def comments_params
        params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController


    def index
        redirect_if_not_logged_in
        @games = Game.all
        if params[:q] && !params[:q].empty?
            @games = @games.search(params[:q].downcase)
        end
    end

    def show
        redirect_if_not_logged_in
        @game = Game.find_by(id: params[:id])
        @user = @game.users
        # binding.pry
    end

   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def new
      redirect_if_not_logged_in
        @post = Post.new
    end

    def create
      redirect_if_not_logged_in
      @game = Game.find_or_create_by(title: post_params[:game_name])
      @post = Post.new(post_params)
      @post.game_id = @game.id
      @post.user_id = current_user.id
      if @post.save
        redirect_to game_post_path(@game, @post)
      else
        render :new
      end
    end

    def edit
      redirect_if_not_logged_in
      @post = Post.find_by(id: params[:id])
    end

    def update
      @game = Game.find_or_create_by(title: post_params[:game_name])
      @post = Post.find_by(id: params[:id])
      @post.game_id = @game.id
      @post.update(post_params)
      if @post.valid?
        redirect_to game_post_path(@game, @post)
      else
        render :edit
      end
    end

    def index
      redirect_if_not_logged_in
        @posts = Post.all
        @game = Game.find_by(id: params[:game_id])
    end

    def show
      redirect_if_not_logged_in
        @game = Game.find_by(id: params[:game_id])
        @post = Post.find_by(id: params[:id])
        @comments = @post.comments
        @comment = Comment.new
    end

    def destroy
      redirect_if_not_logged_in
      @post = Post.find_by(id: params[:id])
      @post.destroy
      redirect_to posts_path
    end

    

    private 

    def post_params
        params.require(:post).permit(:content, :game_name, :gamer_tag, :platform )
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def create
        @user = User.find_by(username: params[:user][:username])
        if @user && @user.authenticate(params[:user][:password])
            flash[:message] = "Succesful sign in"
            session[:user_id] = @user.id
            redirect_to users_path
        else
            flash[:message] = "Invalid Credentials"
            render :new
        end
    end

    def logout
        session.clear
        redirect_to root_path
    end

    def omniauth
        @user = User.find_or_create_by(username: auth[:info][:email]) do |u|
            u.email = auth[:info][:email]
            u.username = auth[:info][:email]
            u.uid = auth[:uid]
            u.provider = auth[:provider]
            u.password = SecureRandom.hex(10)
        end
        
        if @user.valid?
            flash[:messsage] = "Signed IN with GOOGLE GOOD JOb"
            session[:user_id] = @user.id
            redirect_to users_path
        else
            flash[:message] = "Credential error"
            redirect_to login_path
        end
    end

    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
    end

    def index
        @user = User.find_by(id: session[:user_id])
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # def current_user
    #     @user ||= User.find_by_id(session[:user_id])
    # end

    # def logged_in?
    #     !!current_user
    # end
end

app/helpers/posts_helper.rb
module PostsHelper
    def show_post
        @post.gamer_tag
    end
end

app/views/comments/_comment.html.erb
<li>
   <%= comment.user.name.capitalize %> - <%= comment.content %>
</li>

app/views/games/index.html.erb
<h1> All Games</h1>

<%= form_tag("/games", method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
<% end %>

<% @games.each do |game| %>
    <h3> <%= link_to "#{game.title}", game_path(game) %> </h3>
<% end %>

app/views/games/show.html.erb
<h1> All posts for <%= @game.title %>: </h1>

<% @game.posts.each do |gp| %>
    <h3> <%= link_to "#{gp.content}", game_post_path(@game, gp) %></h3>
<% end %>

<h1> All users with posts about <%= @game.title %>: </h1>

<% @names = @user.collect {|user| user.username} %>
    <h3> <%= @names.uniq.join() %> </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SafeHouse</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>

</head>

<body>

 
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">SafeHouse</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if logged_in? %>
            <li>
            <%= link_to 'Browse Games', games_path, class: 'nav-link active' %>
            </li>
            <li>
            <%= link_to 'Create A Post', new_post_path, class: 'nav-link active' %>
            </li>
            <li>
            <%= link_to 'Browse Posts', posts_path, class: 'nav-link active' %>
            </li>
            <li>
            <%= link_to 'LOGOUT', logout_path, class: 'nav-link active', method: 'delete' %>
            </li>
        </ul>

      <% else %>
        <li>
            <%= link_to 'LOGIN', login_path, class: 'nav-link active' %>
        </li>
        <li>
            <%= link_to 'LOGIN WITH GOOGLE', '/auth/google_oauth2', class: 'nav-link active', method: "post" %>
        </li>
        <li>
             <%= link_to 'SIGNUP', signup_path, class: 'nav-link active' %>
        </li>
        
      <% end %>
    </div>
  </div>
</nav>

  <%= flash[:message] %>

    <%= yield %>
</body>
</html>

app/views/posts/edit.html.erb
<%= form_with(model: [@game, @post]) do |f| %>

    <%= f.label :game_name %>
    <%= f.text_field :game_name %><br>

    <%= f.label :gamer_tag %>
    <%= f.text_field :gamer_tag %><br>

    <%= f.label :content %>
    <%= f.text_field :content %><br>

    <%= f.label :platform %>
    <%= f.text_field :platform %><br>

    <%= f.submit "Edit" %>

<% end %>

app/views/posts/index.html.erb
<h1> All Posts </h1><br>

<% @posts.each do |post| %>
    <h2> <%= link_to "#{post.content}", game_post_path(post.game_id, post.id)  %> </h2><br>
<% end %>

app/views/posts/new.html.erb
<h1> New Post </h1>

<%= form_with(model: [@game, @post]) do |f| %>

    <%= f.label :game_name %>
    <%= f.text_field :game_name %><br>

    <%= f.label :gamer_tag %>
    <%= f.text_field :gamer_tag %><br>

    <%= f.label :content %>
    <%= f.text_field :content %><br>

    <%= f.label :platform %>
    <%= f.text_field :platform %><br>

    <%= f.submit %>

<% end %>

app/views/posts/show.html.erb
<h2><%= @post.gamer_tag %></h2>
<h3><%= @post.content %></h3>
<h3><%= @post.game_name %></h3>
<h3><%= @post.platform %></h3>

<%= link_to "Edit Post", edit_post_path %>
<%= link_to "Delete Post", post_path, method: :delete %><br><br><br>


<h2> Comments: </h2>

<% @post.comments.each do |com| %>
<h4> <%= com.content %></h4><br>
<% end %>

<%= form_with(model: [@game, @post, @comment]) do |f| %>
    <%= f.label :comment %>
    <%= f.text_field :content %><br>
    <%= f.submit "Create Comment" %>
<% end %>

app/views/users/index.html.erb
<h1> Welcome <%= @user.username %> </h1>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= form_with(model: @user, url: signup_path) do |f| %>

    <%= f.label :username %><br>
    <%= f.text_field :username %><br>
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1> Welcome <%= @user.username %> </h1>